
spring:
  kafka:
    consumer:
      client-id: sentence
      auto-offset-reset: earliest
      group-id: wordsGroup
    bootstrap-servers: 172.28.1.3:9092
    producer:
      client-id: words

  data:
    cassandra:
      contact-points: 172.28.1.1:9042
      local-datacenter: datacenter1
      keyspace-name: words
      schema-action: create_if_not_exists
